---
title: "Gut-Metabolic-Modules"
author: "John Sterrett"
date: "2023-11-01"
output: html_document

params:
    GMM_filepath: "GMMs.v1.07.txt"
    delete_GMM_file: FALSE
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

pacman::p_load("tidyverse",
               "ggplot2")
# set ggplot theme
theme_set(theme_bw())

```

# Load data
```{r}
ko <- data.table::fread("../seq.f0.0.r0.0.nonhost.humann/all_genefamilies_ko_named.tsv",
                        data.table=F)
rownames(ko) <- ko$`# Gene Family`
ko$`# Gene Family` <- NULL
ko <- ko %>% mutate_all(as.numeric)
colnames(ko) <- colnames(ko) %>% 
    gsub(pattern="_Abundance-RPKs", replacement="")

ko.tax.rows <- rownames(ko) %>% grepl(pattern="\\|")
ko.notax <- ko[!ko.tax.rows,]
ko.tax <- ko[ko.tax.rows,]

metadata <- data.table::fread("../16s-data/16S_meta.txt",
                        data.table=F)

# Samples before DM 33 were stored in PBS, all others (including LG)
is.DM <- grepl("DM", metadata$Sample_ID)
number <- str_split(metadata$Sample_ID, pattern="_") %>% 
    lapply(function(x){x[2]}) %>% 
    unlist() %>% 
    as.numeric()

metadata$storage_method <- rep(NA, nrow(metadata)) %>% as.character()
metadata[((number < 33) & (is.DM)), "storage_method"] <- "PBS"
metadata[is.na(metadata$storage_method), "storage_method"] <- "RNALater"

metadata[is.DM, "Participant"] <- paste0("DM_", number[is.DM])
metadata[!is.DM, "Participant"] <- paste0("LG_", number[!is.DM])

metadata %>% 
    group_by(Participant) %>% 
    summarise(MSM=first(MSM)) %>%
    select(MSM) %>%
    as.data.frame() %>%
    mutate(MSM=as.factor(MSM)) %>%
    summary()

```

# Pull Gut Metabolic Modules
```{r}
add_K_line_to_matrix <- function(GMM.matrix, line, mod.name, mod.number){
    split.line <- str_split(line, "[,\t]")[[1]]
    new.GMM.matrix <- GMM.matrix
    
    for(entry in split.line){
        new.GMM.matrix <- rbind(new.GMM.matrix, c(entry, mod.name, mod.number))
    }
    return(new.GMM.matrix)
    
}


get_GMM_matrix <- function(filepath){
    GMM.fileconts <- readLines(filepath)
    
    GMM.matrix <- matrix(data=c("KEGG","Module","Module ID"), nrow=1, ncol=3)
    for(i in 1:length(GMM.fileconts)){
        line <- GMM.fileconts[i]
        # if new module, get its name and number
        if(grepl("^MF\\d{4}", line)){
            split.line <- str_split(line, "\t")[[1]]
            mod.number <- split.line[1]
            mod.name <- split.line[2]
        }
        # If KO line, add that info to the matrix
        else if(grepl("^K\\d{5}", line)){
            GMM.matrix <- add_K_line_to_matrix(GMM.matrix, line, mod.name, mod.number)
        }
    }
    
    # tidy
    colnames(GMM.matrix) <- GMM.matrix[1,]
    GMM.matrix <- GMM.matrix[2:nrow(GMM.matrix),]
    GMM.matrix <- as.data.frame(GMM.matrix)
    
    GMM.matrix <- GMM.matrix[!is.na(GMM.matrix$KEGG),]
    GMM.matrix <- GMM.matrix[GMM.matrix$KEGG!="",]
    
    return(GMM.matrix)
}

if(!file.exists(params$GMM_filepath)){
    download.file("https://raw.githubusercontent.com/raeslab/GMMs/master/GMMs.v1.07.txt", 
              params$GMM_filepath)    
}

GMM.matrix <- get_GMM_matrix("GMMs.v1.07.txt")

if(params$delete_GMM_file){
    file.remove(params$GMM_filepath)
}

```


# Get GMM sums for each sample
## Convert to Relative Abundance 
```{r}
ko.notax.rel <- t(t(ko.notax)/colSums(ko.notax)) %>% as.data.frame()
dim(ko.notax.rel)
```

## Parse just the KOs
```{r}
ko.ids <- rownames(ko.notax) %>% 
    str_split(":") %>% 
    lapply(FUN=function(x){x[1]}) %>%
    unlist()
```

## Merge the dataframes
```{r}
ko.notax.rel.GMM <- ko.notax.rel
ko.notax.rel.GMM$ko_ids <- ko.ids
summed.GMM.rels <- merge(ko.notax.rel.GMM, GMM.matrix, 
                         by.x="ko_ids", by.y="KEGG", all=T) %>%
    group_by(Module) %>%
    summarise(across(where(is.numeric), function(x){sum(x, na.rm=T)})) %>%
    as.data.frame()

summed.GMM.rels[is.na(summed.GMM.rels$Module), "Module"] <- "NA"
rownames(summed.GMM.rels) <- summed.GMM.rels$Module
summed.GMM.rels$Module <- NULL

summed.GMM.rels[complete.cases(summed.GMM.rels),]

```
