---
title: "Microbe Functional"
author: "John Sterrett"
date: "2023-10-15"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

pacman::p_load("tidyverse",
               "ggplot2")
# set ggplot theme
theme_set(theme_bw())
```

# Load Data
```{r}
gf <- data.table::fread("../seq.f0.0.r0.0.nonhost.humann/all_genefamilies.tsv",
                        data.table=F)
rownames(gf) <- gf$`# Gene Family`
gf$`# Gene Family` <- NULL
gf <- gf %>% mutate_all(as.numeric)
colnames(gf) <- colnames(gf) %>% 
    gsub(pattern="_Abundance-RPKs", replacement="")

gf.tax.rows <- rownames(gf) %>% grepl(pattern="\\|")
gf.notax <- gf[!gf.tax.rows,]
gf.tax <- gf[gf.tax.rows,]

metadata <- data.table::fread("../16s-data/16S_meta.txt",
                        data.table=F)

# Samples before DM 33 were stored in PBS, all others (including LG)
is.DM <- grepl("DM", metadata$Sample_ID)
number <- str_split(metadata$Sample_ID, pattern="_") %>% 
    lapply(function(x){x[2]}) %>% 
    unlist() %>% 
    as.numeric()

metadata$storage_method <- rep(NA, nrow(metadata)) %>% as.character()
metadata[((number < 33) & (is.DM)), "storage_method"] <- "PBS"
metadata[is.na(metadata$storage_method), "storage_method"] <- "RNALater"

metadata[is.DM, "Participant"] <- paste0("DM_", number[is.DM])
metadata[!is.DM, "Participant"] <- paste0("LG_", number[!is.DM])

metadata %>% 
    group_by(Participant) %>% 
    summarise(MSM=first(MSM)) %>%
    select(MSM) %>%
    as.data.frame() %>%
    mutate(MSM=as.factor(MSM)) %>%
    summary()
```

# Unmapped
```{r}
sample.sums <- colSums(gf)
percent.unmapped <- as.numeric((gf["UNMAPPED",]/sample.sums) * 100)
names(percent.unmapped) <- colnames(gf)

hist(percent.unmapped)

knitr::kable(percent.unmapped, col.names="Percent unmapped")
```

# PCoA {.tabset}

## Aitchison distance {.tabset}
```{r calc_dist}
notax.aitch <- robCompositions::aDist(t(gf.notax)+1)
tax.aitch <- robCompositions::aDist(t(gf.tax)+1)
```

### No-tax by HIV {.tabset}
#### Labeled
```{r pcoa_aitch_HIV}
notax.aitch.pcoa <- ape::pcoa(notax.aitch)

notax.aitch.pcoa.dat <- merge(notax.aitch.pcoa$vectors, metadata,
                              by.x="row.names", by.y="Sample_ID")
notax.aitch.pcoa.dat %>%
    ggplot(mapping=aes(Axis.1, Axis.2, color=HIV_Status, label=Row.names)) +
    geom_point(size=4) +
    ggrepel::geom_label_repel(color="black")
    
```

#### Not Labeled

```{r pcoa_aitch_HIV_nl}
notax.aitch.pcoa <- ape::pcoa(notax.aitch)

notax.aitch.pcoa.dat <- merge(notax.aitch.pcoa$vectors, metadata,
                              by.x="row.names", by.y="Sample_ID")
notax.aitch.pcoa.dat %>%
    ggplot(mapping=aes(Axis.1, Axis.2, color=HIV_Status, label=Row.names)) +
    geom_point(size=4)
    
```

### No-tax by Cohort {.tabset}
#### Labeled
```{r pcoa_aitch_Cohort}
notax.aitch.pcoa.dat <- merge(notax.aitch.pcoa$vectors, metadata,
                              by.x="row.names", by.y="Sample_ID")
notax.aitch.pcoa.dat %>%
    ggplot(mapping=aes(Axis.1, Axis.2, color=MSM, label=Row.names)) +
    geom_point(size=4) +
    ggrepel::geom_label_repel(color="black")
    
```

#### Not Labeled
```{r pcoa_aitch_Cohort_nl}
notax.aitch.pcoa.dat <- merge(notax.aitch.pcoa$vectors, metadata,
                              by.x="row.names", by.y="Sample_ID")
notax.aitch.pcoa.dat %>%
    ggplot(mapping=aes(Axis.1, Axis.2, color=MSM, label=Row.names)) +
    geom_point(size=4)
    
```

### No-tax by storage method {.tabset}
#### Labeled
```{r pcoa_aitch_storage}
notax.aitch.pcoa.dat %>%
    ggplot(mapping=aes(Axis.1, Axis.2, color=storage_method, label=Row.names)) +
    geom_point(size=4) +
    ggrepel::geom_label_repel(color="black")
    
```

#### Not Labeled
```{r pcoa_aitch_storage_nl}
notax.aitch.pcoa.dat %>%
    ggplot(mapping=aes(Axis.1, Axis.2, color=storage_method, label=Row.names)) +
    geom_point(size=4)
    
```


### With tax by HIV
```{r pcoa_aitch_HIV_tax}
tax.aitch.pcoa <- ape::pcoa(tax.aitch)

tax.aitch.pcoa.dat <- merge(tax.aitch.pcoa$vectors, metadata,
                              by.x="row.names", by.y="Sample_ID")
tax.aitch.pcoa.dat %>%
    ggplot(mapping=aes(Axis.1, Axis.2, color=HIV_Status, label=Row.names)) +
    geom_point(size=4) +
    ggrepel::geom_label_repel(color="black")
    
```

### With tax by Cohort
```{r pcoa_aitch_Cohort_tax}
tax.aitch.pcoa.dat %>%
    ggplot(mapping=aes(Axis.1, Axis.2, color=MSM, label=Row.names)) +
    geom_point(size=4) +
    ggrepel::geom_label_repel(color="black")
    
```

### With tax by storage method
```{r pcoa_aitch_storage_tax}
tax.aitch.pcoa.dat %>%
    ggplot(mapping=aes(Axis.1, Axis.2, color=storage_method, label=Row.names)) +
    geom_point(size=4) +
    ggrepel::geom_label_repel(color="black")
    
```


# Pathways
## Load and clean
```{r}
paths <- data.table::fread("../seq.f0.0.r0.0.nonhost.humann/all_pathabundance.tsv")

rownames(paths) <- paths$`# Pathway`
paths$`# Pathway` <- NULL
colnames(paths) <- colnames(paths) %>% gsub(pattern="_Abundance", 
                                            replacement="")

paths.tax.rows <- grepl("\\|", rownames(paths))

paths.tax <- paths[paths.tax.rows,]
rownames(paths.tax) <- rownames(paths)[paths.tax.rows]
paths.tax.rel <- t(t(paths.tax)/colSums(paths.tax))

paths.notax <- paths[!paths.tax.rows,]
rownames(paths.notax) <- rownames(paths)[!paths.tax.rows]
paths.notax.rel <- t(t(paths.notax)/colSums(paths.notax))
rownames(paths.notax.rel) <- rownames(paths.notax)
```

## Top Paths
```{r}
order.of.pathways <- order(rowSums(paths.notax.rel), decreasing=T)

path.notax.rel.sorted <- paths.notax.rel[order.of.pathways,] 
rownames(path.notax.rel.sorted) <- rownames(paths.notax.rel)[order.of.pathways]

pathway.means.sorted <- path.notax.rel.sorted %>%
    rowMeans() 

(pathway.means.sorted*100) %>% 
    round(digits=2) %>%
    head(n=20) %>%
    knitr::kable()

integrated.p.m.s <- (pathway.means.sorted[!(names(pathway.means.sorted) 
                       %in% c("UNMAPPED", "UNINTEGRATED"))]) 
((integrated.p.m.s/sum(integrated.p.m.s)) * 100) %>% 
    round(digits=2) %>%
    head(n=20) %>%
    knitr::kable()

```