---
title: "Read counts by filter method"
author: "John Sterrett"
date: "2023-10-12"
output: html_document
---

```{r setup, include=FALSE}
pacman::p_load(ggplot2,
               tidyverse,
               ThemePark,
               ggbeeswarm)
knitr::opts_chunk$set(echo = TRUE)

# set ggplot theme
theme_set(theme_bw())
```

# Load data

```{r load}
df <- data.table::fread("../read_counts_per_sample_by_filt_method.tsv")
metadata <- data.table::fread("../metadata.csv")
```

# Clean data

```{r clean}
df$V1 <- NULL
df$Sample <- 
    df$file %>% sapply(FUN=function(x){str_split(x, "/")[[1]][2]})
df$Sample <- gsub(pattern=".fq.gz", replacement="", df$Sample)
df$Sample <- gsub(pattern=".R1", replacement="", df$Sample)
df$Sample <- gsub(pattern=".nonhuman", replacement="", df$Sample)

df$filt_method <- grepl("nonhost", df$file) %>% as.factor()
df[df$filt_method==T, "filt_method"] <- "Hostile"
df[df$filt_method==F, "filt_method"] <- "Bbmap"

# Divide this by 2 because this file includes both of the paired reads
df[df$filt_method=="Bbmap", "readcounts"] <- df[df$filt_method=="Bbmap", "readcounts"]/2
df$million_reads <- df$readcounts/1e6


metadata$start_reads <- as.numeric(gsub(",", "", metadata$`PF Clusters`)) +
    as.numeric(gsub(",", "", metadata$`PF Clusters_2`))

df <- merge(metadata[,c("Sample", "start_reads")], 
            df, 
            by="Sample",
            all.y=TRUE)
```

# Plot
## Histogram of non-host read counts
```{r plot}
hist(df$million_reads)
```

## Boxplot of non-host read counts by filtering method
```{r box_by_filt} 
ggplot(data=df, 
       mapping=aes(x=filt_method,
                   y=million_reads)) +
    geom_boxplot() +
    geom_line(aes(group=Sample)) + 
    geom_point(size = 2) +
    labs(x="Host filtering method", 
         y="Million non-host reads")
```

## Violinplot of non-host read counts by filtering method
```{r}
ggplot(data=df, 
       mapping=aes(x=filt_method,
                   y=million_reads)) +
    geom_violin() +
    geom_line(aes(group=Sample)) + 
    geom_point(size = 2) +
    labs(x="Host filtering method", 
         y="Million non-host reads")

```

## Non-host reads by prep method {.tabset}
### Prep
```{r prep_by_prep}
# Samples before DM 33 were stored in PBS, all others (including LG)
is.DM <- grepl("DM", df$Sample)
number <- str_split(df$Sample, pattern="_") %>% 
    lapply(function(x){x[2]}) %>% 
    unlist() %>% 
    as.numeric()

df$storage_method <- rep(NA, nrow(df)) %>% as.character()
df[((number < 33) & (is.DM)), "storage_method"] <- "PBS"
df[is.na(df$storage_method), "storage_method"] <- "RNALater"
```

### Absolute read number {.tabset}
#### Faceted
```{r plot_by_prep_absolute_faceted} 
ggplot(data=df, 
       mapping=aes(x=storage_method,
                   y=million_reads)) +
    geom_violin() +
    geom_beeswarm() +
    facet_wrap(~filt_method) +
    labs(x="Storage method", y="Million non-host reads")
```

#### Non-faceted (Hostile only)
```{r plot_by_prep_absolute} 
ggplot(data=df %>% filter(filt_method=="Hostile"), 
       mapping=aes(x=storage_method,
                   y=million_reads)) +
    geom_violin() +
    geom_beeswarm() +
    labs(x="Storage method", y="Million non-host reads")
```


### Percent {.tabset}
#### Faceted
```{r plot_by_prep_relative_faceted} 
ggplot(data=df, 
       mapping=aes(x=storage_method,
                   y=(readcounts/start_reads)*100 )) +
    geom_violin() +
    geom_beeswarm() +
    facet_wrap(~filt_method) +
    labs(x="Storage method", y="Non-host reads (% of total)")
```

#### Non-faceted (Hostile only)
```{r plot_by_prep_relative} 
ggplot(data=df %>% filter(filt_method=="Hostile"), 
       mapping=aes(x=storage_method,
                   y=(readcounts/start_reads)*100 )) +
    geom_violin() +
    geom_beeswarm() +
    labs(x="Storage", y="Non-host reads (% of total)") +
    ylim(c(0, 22))
```

```{r}
perc_nonhost <- (df$readcounts/df$start_reads)*100 
t.test(perc_nonhost[df$storage_method=="PBS"],
       perc_nonhost[df$storage_method=="RNALater"])
```